---
_ipv6_network_interface_global_alias: '{{ (ansible_enp0s9.ipv6 | selectattr("scope", "equalto", "global") | list | first) }}'
bird_router_id: '{{ ansible_enp0s8.ipv4.address }}'
bird_carry_static_routes:
  - my_network:
    cidr: "{{ (_ipv6_network_interface_global_alias.address ~ '/' ~ _ipv6_network_interface_global_alias.prefix) | ipaddr('net') }}"
    via: enp0s9
