---
bird_router_id: 10.8.99.1
bird_as_number: 64783
bird_neighbors:
  - router_a:
    local_ip_address: 192.168.2.2
    remote_ip_address: 192.168.2.1
    remote_as_number: 64781
  - router_b:
    local_ip_address: 192.168.3.2
    remote_ip_address: 192.168.3.1
    remote_as_number: 64782
bird_carry_routes:
  - { cidr: '10.8.99.0/24', interface: 'enp0s9' }
